# Generated by Django 4.1.6 on 2023-02-04 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_drink_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drink",
            name="user",
        ),
    ]
