# Generated by Django 4.1.6 on 2023-02-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_remove_drink_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="drink",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="image/"),
        ),
    ]
