# Generated by Django 4.1.6 on 2023-02-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_drink_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drink",
            name="image",
            field=models.CharField(max_length=40, null=True),
        ),
    ]
