# Generated by Django 4.1.6 on 2023-02-05 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_cart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="total",
            new_name="amount",
        ),
    ]
