# Generated by Django 4.1.6 on 2023-02-05 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_rename_total_cart_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="amount",
        ),
    ]
