# Generated by Django 4.1.6 on 2023-02-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_cart_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="amount",
        ),
        migrations.AddField(
            model_name="drink",
            name="amount",
            field=models.IntegerField(null=True),
        ),
    ]
