# Generated by Django 4.1.6 on 2023-02-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_remove_cart_amount_drink_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drink",
            name="amount",
        ),
        migrations.AddField(
            model_name="cart",
            name="amount",
            field=models.IntegerField(null=True),
        ),
    ]
