# Generated by Django 4.1.5 on 2023-02-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_remove_drink_amount_cart_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
