# Generated by Django 4.1.5 on 2023-02-06 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_cart_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="name",
        ),
    ]
