# Generated by Django 4.1.2 on 2023-02-13 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_remove_cart_user_customer_cart_customer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer", old_name="user", new_name="name",
        ),
        migrations.RemoveField(model_name="cart", name="customer",),
        migrations.RemoveField(model_name="customer", name="address",),
        migrations.RemoveField(model_name="customer", name="phone",),
        migrations.AddField(
            model_name="customer",
            name="cart",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="base.cart"
            ),
        ),
    ]
