# Generated by Django 4.1.5 on 2023-02-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_remove_cart_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
