# Generated by Django 4.1.2 on 2023-02-13 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0019_customer"),
    ]

    operations = [
        migrations.DeleteModel(name="Customer",),
    ]
