# Generated by Django 4.1.2 on 2023-02-21 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0021_order_customer"),
    ]

    operations = [
        migrations.DeleteModel(name="Order",),
    ]
