# Generated by Django 4.1.2 on 2023-02-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0023_remove_cart_user_cart_customer_alter_customer_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="customer", name="phone", field=models.CharField(max_length=500),
        ),
    ]
